# Generated by Django 5.1 on 2024-10-14 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choozy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='country_code',
            field=models.CharField(default='', max_length=2),
        ),
    ]
