# Generated by Django 5.1 on 2024-10-17 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choozy', '0003_alter_room_country_code_alter_room_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='latitude',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='longitude',
            field=models.FloatField(blank=True),
        ),
    ]
