# Generated by Django 5.1 on 2024-10-17 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choozy', '0004_alter_room_latitude_alter_room_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='longitude',
            field=models.FloatField(null=True),
        ),
    ]
