# Generated by Django 5.1 on 2024-10-20 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choozy', '0005_alter_room_latitude_alter_room_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='game_code',
        ),
        migrations.AddField(
            model_name='player',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
