# Generated by Django 5.1 on 2024-11-12 10:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choozy', '0006_remove_player_game_code_player_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.TextField()),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('parking', models.BooleanField(default=False)),
                ('outdoor', models.BooleanField(default=False)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='choozy.player')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='choozy.room')),
            ],
        ),
    ]
