# Generated by Django 5.1 on 2024-11-18 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('choozy', '0007_response'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='code',
        ),
    ]
