# Generated by Django 5.1 on 2024-11-18 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('choozy', '0008_remove_room_code'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Response',
            new_name='Submission',
        ),
    ]
