# Generated by Django 5.1 on 2024-11-23 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('choozy', '0010_reslults'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reslults',
            new_name='Reslult',
        ),
    ]
